# language: ruby
# rvm:
#   - 2.4.0
# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=c3353dd4f0b28006de8c2b9cba681bc52010aa676bef64663696d9b897cb0797 # IMPORTANT!!!! REPLACE ABC123 WITH THE CODE CLIMATE ID
language: ruby
rvm:
  - 2.4.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
